version: '3'

services:
  db:
    image: postgres
    container_name: ibm_test_db
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./roles.sql:/home/roles.sql